### ISSUE TITLE
`ChemicalState` naming

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#11]
Related discussion

https://github.com/OpenFreeEnergy/gufe/pull/1

https://github.com/OpenFreeEnergy/gufe/pull/3#discussion_r837001993

The container class for `Component`s needs a good name.  We currently landed on `ChemicalState` after `Microstate` was deemed too much of a loaded stat-mech term. @jchodera suggested `ChemicalSystem`, `ComponentCollection`, or `ChemicalComponents` all of which seem appropriate.

I think I like `ComponentCollection` as it describes what it does, with `ChemicalSystem` second as it describes what we're trying to express with the obejct.

**Comment by IAlibay** [comment]
My vote would be ChemicalSystem, I generally like the idea of being able to say that what happens in the edges are AlchemicalSystems

**Comment by dwhswenson** [comment]
I'm in favor of getting away from anything with `State`, as that tends to be a term that is quickly overloaded.

`ChemicalSystem` and `AlchemicalSystem` would imply to me that the two implement similar APIs (as much duck-typing as possible). Is this the plan? If so, I'm in favor of this. Otherwise, I lean a little toward `ChemicalComponents` but think that `ComponentCollection` is about equally as good.

**Comment by IAlibay** [comment]
> `ChemicalSystem` and `AlchemicalSystem` would imply to me that the two implement similar APIs (as much duck-typing as possible). Is this the plan?

yeah you're right I guess they won't be the same (indeed `AlchemicalSystem` probably won't even exist)

**Comment by dwhswenson** [comment]
Ah, if there's no `AlchemicalSystem`, then `ChemicalSystem` is fine -- I just meant that if both exist then they should be as similar as possible.

Thinking more, I do slightly lean toward something with `Chemical` in the name to avoid possible namespace confusion, since `ComponentCollection` could just as easily come from a non-chemical library (quick GitHub search shows about 150k times people have used `ComponentCollection` in code, though vast majority are due to [CakePHP](https://api.cakephp.org/2.4/class-ComponentCollection.html). Compare with ~1k for `ChemicalSystem` and a whopping 51 for `ChemicalComponents`.)
