### ISSUE TITLE
Inccorect connectivity with modified amino acids

### ISSUE THREAD

**Issue by jthorton** [OpenFreeEnergy/gufe#298]
When loading a protein with a modified amino acid, in this case, two phosphorylated tyrosines, the connectivity is incorrectly interpreted as 0 which causes the atoms to be identified as ions and an error is raised. It seems like the bond order [here](https://github.com/OpenFreeEnergy/gufe/blob/29f98ec0227ed9f30ea6b84096dc13818a9ac8d3/gufe/components/proteincomponent.py#L180) is being set to `BondType.UNSPECIFIED` despite the connect records in the pdb file.

[jak2_FEP_receptor_RELAXED_capped.txt](https://github.com/OpenFreeEnergy/gufe/files/14640218/jak2_FEP_receptor_RELAXED_capped.txt)

**Comment by richardjgowers** [comment]
@jthorton Sorry for the short reply, this is from an airport... The current `from_pdbfile` loading is vendored from OpenMM, it's a bit limited and restricted to standard AAs.  We're looking to do something smarter eventually... see #135 I've got a pet project here:  https://github.com/OpenFreeEnergy/pdbinf

Basically your PDB file is wrong, residues 1007 and 1008 should be resname PTR not TYR.  (As a second gripe, CONECT records shouldn't make a difference for residues labelled as ATOM rather than HETATM etc).  If I download the cif template from here: https://www.rcsb.org/ligand/PTR I can then load via pdbinf to rdkit, then gufe can ingest this rdkit mol.

<img width="1123" alt="image" src="https://github.com/OpenFreeEnergy/gufe/assets/9249543/7ab6c280-a504-4475-8811-f7ca51abca94">

Longer term, there's also code I'm playing with that does this residue guessing automatically, see: https://github.com/OpenFreeEnergy/pdbinf/blob/main/notebooks/tpo_guessing_demo.ipynb. This should make it just magically work even if things are labelled incorrectly etc

**Comment by richardjgowers** [comment]
also this paper/software is somewhat relevant: https://jcheminf.biomedcentral.com/articles/10.1186/s13321-023-00786-w

**Comment by jthorton** [comment]
Thanks @richardjgowers this is testing my system preparation skills and they still need some work! I tried the suggested pathway and it worked great, the demo notebook looks fantastic as well excited to see this be part of gufe!

**Comment by richardjgowers** [comment]
Ok cool, glad it worked.  Yeah one thing holding up switching the backend is we/I have a lot of confidence in the OpenMM vendored bit as it's had a lot of usage, and there's much less usage gone into pdbinf so far; so it's good that it's worked for you on this corner case!
