### ISSUE TITLE
Flyweight pattern not working on Transformation

### ISSUE THREAD

**Issue by richardjgowers** [OpenFreeEnergy/gufe#88]
Looks like the flyweight pattern isn't working for a `Transformation`

https://github.com/OpenFreeEnergy/gufe/blob/main/gufe/tokenization.py#L252

Code to reproduce:
```
t1 = Transformation(...)

t1.dump('out.json')

t2 = Transformation.load('out.json')

t1 == t2  # great

t1 is t2  # isn't the same memory
```

**Comment by dwhswenson** [comment]
What happens if you to the `to_dict`/`from_dict` cycle?

```python
t2 = Transformation.from_dict(t1.to_dict())
t1 is t2
```

(I can try to debug this later, but this will give me a lot of information)

**Comment by richardjgowers** [comment]
Yeah I've not had time to dig, I just saw the reprs were different and wanted to raise the issue before I moved on

```python
t2 = openfe.setup.Transformation.from_dict(trans.to_dict())

t2 is trans  # False
```

Even if I go straight to the method which seems to query the `TOKENIZABLE_REGISTRY` I can't get the same object:

```python
t3 = gufe.tokenization.from_dict(trans.to_dict())

t3 is trans  # False
```
That t3 isn't even equal to the original transformation, so not sure what that function even does tbh

**Comment by dwhswenson** [comment]
Can you check their `key` attributes? If those aren't different, then something is wrong in the tokenization (which would explain why it isn't getting picked up). Will start digging on my side soon.

**Comment by dwhswenson** [comment]
Can't reproduce. Issue isn't at the transformation level, but something in one of the other objects you have. Do you test your protocol as a `GufeTokenizable` (using the mix-in?)

```python
In [1]: import gufe
   ...: from gufe.tests.test_protocol import DummyProtocol
   ...: from gufe.tests.conftest import benzene_modifications
   ...: benzene_modifications = benzene_modifications.__pytest_wrapped__.obj()
LICENSE: Could not open license file "oe_license.txt" in local directory
LICENSE: N.B. OE_LICENSE environment variable is not set
LICENSE: N.B. OE_DIR environment variable is not set
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!
LICENSE: No product keys!

In [2]: benzene = gufe.SmallMoleculeComponent(rdkit=benzene_modifications['benzene'])
   ...: toluene = gufe.SmallMoleculeComponent(rdkit=benzene_modifications['toluene'])
   ...: benz = gufe.ChemicalSystem({'ligand': benzene})
   ...: tol = gufe.ChemicalSystem({'ligand': toluene})

In [3]: trans = gufe.Transformation(stateA=benz, stateB=tol, protocol=DummyProtocol())

In [4]: t1 = gufe.Transformation.from_dict(trans.to_dict())
   ...: t1 == trans
Out[4]: True

In [5]: t1 is trans
Out[5]: True

In [6]: trans.dump("foo.json")
   ...: t2 = trans.load("foo.json")

In [7]: t2 is trans
Out[7]: True
```

**Comment by dwhswenson** [comment]
> Even if I go straight to the method which seems to query the `TOKENIZABLE_REGISTRY` I can't get the same object:
> 
> ```python
> t3 = gufe.tokenization.from_dict(trans.to_dict())
> 
> t3 is trans  # False
> t3 == trans  # False
> ```
> 
> That t3 isn't even equal to the original transformation, so not sure what that function even does tbh

This is expected. `gufe.tokenization.from_dict` is about replacing existing key-encoded objects by the actual objects. `obj.to_dict` is a deep dictionary. There is no key encoding. For mine, I see the following:

<p><code>
In [8]: gufe.tokenization.from_dict(trans.to_dict())
Out[8]: Transformation(stateA={'components': {'ligand': {'atoms': [(6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, '')], 'bonds': [(0, 1, 2, True, ''), (0, 5, 1, True, ''), (0, 6, 1, False, ''), (1, 2, 1, True, ''), (1, 7, 1, False, ''), (2, 3, 2, True, ''), (2, 8, 1, False, ''), (3, 4, 1, True, ''), (3, 9, 1, False, ''), (4, 5, 2, True, ''), (4, 10, 1, False, ''), (5, 11, 1, False, '')], 'name': 'benzene', 'conformers': ["\x93NUMPY\x01\x00v\x00{'descr': '>f8', 'fortran_order': False, 'shape': (12, 3), }                                                         \n@9Ãº^5?|Ã®@\x15NÃ\x16\x87+\x02@\x13\x1dÂ²-\x0eV\x04@:e\x1eÂ¸QÃ«\x85@\x14KÃÂ§Ã¯\x9dÂ²@\x0bÃ½Ã³Â¶EÂ¡Ã@;W\n=pÂ£Ã@\x17pÂ£Ã\n=q@\x077KÃÂ§Ã¯\x9e@;ÃEÂ¡ÃÃ\x83@\x1bÂ¯\x1a\x9fÂ¾vÃ@\x0c\x8dOÃ;dZ@;k\x85\x1eÂ¸QÃ¬@\x1cÃÂ´9X\x10b@\x13l\x8bC\x95\x81\x06@:\x7f|Ã\x91hs@\x19\x84\x18\x93tÂ¼j@\x15Ã A\x897KÃ@9:Ã,<\x9eÃ@\x12Â¾\\\x91ÃN<@\x14ÃºÃ»~\x90Ã¿\x97@9Ã·Â´Â¢3\x9c\x0f@\x10Ã°Â¾\rÃ(\x8d@\x07\x98Ã¼PH\x16Ã°@;Â°bMÃÃ±Âª@\x16\x86?\x14\x12\x05Â¼?Ã¾RT`ÂªdÃ@<\x92Â° Ã\x9bÂ¦@\x1eC\x95\x81\x06$Ã@\x08Â¶\x114\x04ÃªK@;Ã&\x80\x9dIR@ \x1e\x9e\x1b\x08\x9a\x02@\x15\x8b\x92:)Ãz@:/Ã¹rGE9@\x1aIÂº^5?}@\x19Ã»Â²Ã¾Ãm]"], '__qualname__': 'SmallMoleculeComponent', '__module__': 'gufe.components.smallmoleculecomponent'}}, 'box_vectors': [nan, nan, nan, nan, nan, nan, nan, nan, nan], 'name': '', '__qualname__': 'ChemicalSystem', '__module__': 'gufe.chemicalsystem'}, stateB={'components': {'ligand': {'atoms': [(1, '', 0, False, ''), (1, '', 0, False, ''), (6, '', 0, False, ''), (1, '', 0, False, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (6, '', 0, True, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, ''), (1, '', 0, False, '')], 'bonds': [(0, 2, 1, False, ''), (1, 2, 1, False, ''), (2, 3, 1, False, ''), (4, 5, 2, True, ''), (4, 9, 1, True, ''), (4, 10, 1, False, ''), (5, 6, 1, True, ''), (5, 11, 1, False, ''), (6, 7, 2, True, ''), (6, 12, 1, False, ''), (7, 8, 1, True, ''), (7, 13, 1, False, ''), (2, 8, 1, False, ''), (8, 9, 2, True, ''), (9, 14, 1, False, '')], 'name': 'toluene', 'conformers': ['\x93NUMPY\x01\x00v\x00{\'descr\': \'>f8\', \'fortran_order\': False, \'shape\': (15, 3), }                                                         \n@<Ã¨>BZÃ®c@!|\x9eÃ¬Â¿Â±[@\x14|Ã\x91hrÂ°@<2T`ÂªdÃ@ I^\x9e\x1b\x08\x9a@\x1a\x8eÂ¤Â¨ÃTÃ@;Ã¼\x84ÂµÃÃ?@ Ã2a|\x1bÃ@\x16kÂ¹\x8c~($@;B\x05Â¼\x01Â£n@"t,<\x9eÃ¬Ã@\x16UÃÂªÃ\x9e\x84@9Ãº^5?|Ã®@\x15NÃ\x16\x87+\x02@\x13\x1dÂ²-\x0eV\x04@:e\x1eÂ¸QÃ«\x85@\x14KÃÂ§Ã¯\x9dÂ²@\x0bÃ½Ã³Â¶EÂ¡Ã@;W\n=pÂ£Ã@\x17pÂ£Ã\n=q@\x077KÃÂ§Ã¯\x9e@;ÃEÂ¡ÃÃ\x83@\x1bÂ¯\x1a\x9fÂ¾vÃ@\x0c\x8dOÃ;dZ@;k\x85\x1eÂ¸QÃ¬@\x1cÃÂ´9X\x10b@\x13l\x8bC\x95\x81\x06@:\x7f|Ã\x91hs@\x19\x84\x18\x93tÂ¼j@\x15Ã A\x897KÃ@9:Ã,<\x9eÃ@\x12Â¾\\\x91ÃN<@\x14ÃºÃ»~\x90Ã¿\x97@9Ã·Â´Â¢3\x9c\x0f@\x10Ã°Â¾\rÃ(\x8d@\x07\x98Ã¼PH\x16Ã°@;Â°bMÃÃ±Âª@\x16\x86?\x14\x12\x05Â¼?Ã¾RT`ÂªdÃ@<\x92Â° Ã\x9bÂ¦@\x1eC\x95\x81\x06$Ã@\x08Â¶\x114\x04ÃªK@:/Ã¹rGE9@\x1aIÂº^5?}@\x19Ã»Â²Ã¾Ãm]'], '__qualname__': 'SmallMoleculeComponent', '__module__': 'gufe.components.smallmoleculecomponent'}}, 'box_vectors': [nan, nan, nan, nan, nan, nan, nan, nan, nan], 'name': '', '__qualname__': 'ChemicalSystem', '__module__': 'gufe.chemicalsystem'}, protocol={'settings': None, '__qualname__': 'DummyProtocol', '__module__': 'gufe.tests.test_protocol'})
</code></p>


You're assigning a dict representation of components instead of the recreated object. Essentially, `gufe.tokenization.from_dict` expects a shallow dict, you're giving it a deep one.

**Comment by dwhswenson** [comment]
> Do you test your protocol as a `GufeTokenizable` (using the mix-in?)

Added a paragraph on how to use the mix-in as part of the in-progress https://github.com/OpenFreeEnergy/gufe/pull/81.

**Comment by dwhswenson** [comment]
issue solved
